config/routes.rb
Bloccit::Application.routes.draw do
  get "comments/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:show] #create a route for users#show

  resources :topics do
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]

      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get
  match "topics" => 'topics', via: :get

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :topic, :image
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  default_scope order('rank DESC')
  scope :visible_to, lambda { |user| user ? scoped : joins(:topic).where('topics.public' => true) }

  after_create :create_vote

  mount_uploader :image, ImageUploader

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  def points
    self.votes.sum(:value).to_i
  end

  default_scope order('created_at DESC')

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def update_rank
    age = (self.created_at - Time.new(1970,1,1)) / 86400
    new_rank = points + age

    self.update_attribute(:rank, new_rank)
  end

  private

  # Who ever created a post, should automatically be set to "voting" it up.
  def create_vote
    self.user.votes.create(value: 1, post: self)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    authorize! :read, @topic, message: "You must be signed in to view this post."
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a new post."
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic

    authorize! :create, @post, message: "You need to be signed up to do that."
    if @post.save
      redirect_to [@topic, @post], notice: "Post was saved successfully."
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      redirect_to [@topic, @post], notice: "Post was saved successfully."
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @post = Post.find(params[:id])

    title = @post.title

    authorize! :destroy, @post, message: "You need to own this post to delete it."
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for [topic, post], html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :title, label: 'Title' %>
  <%= f.input :body %>
  <div class="control-group">
    <%= f.label :image, class: 'control-label' %>
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

<%= form_for [topic, post], html: { class: 'form-horizontal' } do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(post.errors.count, "error") %> errors.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { topic: post.topic, post: post } %>
  <%= link_to [post.topic, post], class: 'pull-left' do %>
    <%= image_tag(post.image.thumb.url) if post.image? %>
  <% end %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to (markdown post.title), [post.topic, post] %>
    </h4>
    <small>
      <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
      submitted <%= time_ago_in_words(post.created_at) %> ago by
      <%= link_to post.user.name, post.user %><br/>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>

  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% if can? :create, Post %>
  <%= link_to "New Post", new_post_path, class: 'btn btn-primary btn-mini' %>
<% end %>

<% @posts.each do |post| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to post.title, post %>
      </h4>
      <small>
        submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
        <%= post.comments.count %> Comments
      </small>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="span8">
    <%= render partial: 'votes/voter', locals: { topic: @topic, post: @post } %>
    <h1><%= markdown @post.title %></h1>

    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
    <p><%= image_tag(@post.image.url) %></p>

    <hr/>

    <!-- Display Comments -->
    <h2><%= @comments.count %> Comments</h2>

    <%= render @comments %>

    <% if can? :create, Comment %>
      <hr/>
      <h4>New Comment</h4>
      <%= render partial: 'comments/form', locals: { topic: @topic, post: @post, comment: @comment } %>
    <% end %>
  </div>
  <div class="span4">
    <% if can? :edit, @post %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-mini' %>
    <% end %>
    <% if can? :destroy, @post %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this post?' %>
    <% end %>

    <div>
      <h3><%= pluralize(@post.points, 'point') %></h3>
      <small>
        <%= pluralize(@post.up_votes, 'up vote') %>
        <%= pluralize(@post.down_votes, 'down vote') %>
      </small>
    </div>
    <%= render partial: 'favorites/favorite', locals: { topic: @topic, post: @post } %>

  </div>
</div>