config/routes.rb
Bloccit::Application.routes.draw do
  get "comments/create"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:show] #create a route for users#show

  resources :topics do
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]

      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get
  match "topics" => 'topics', via: :get

  root to: 'welcome#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  attr_accessible :value, :post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }

  after_save :update_post

  def up_vote?
  	value == 1
  end

  def down_vote?
  	value == -1
  end

  private

  def update_post
    self.post.update_rank
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :setup

  def up_vote
    update_vote(1)
    redirect_to :back
  end

  def down_vote
    update_vote(-1)
    redirect_to :back
  end

  private

  def setup
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.find(params[:post_id])
    authorize! :create, Vote, message: "You need to be a user to vote."

    @vote = @post.votes.where(user_id: current_user.id).first
  end

  def update_vote(new_value)
     if @vote # If the vote exists, update it
      @vote.update_attribute(:value, new_value)
    else # Create the vote if it does not exist
      @vote = current_user.votes.create(value: 1, post: @post)
    end
  end

end

app/views/votes/_voter.html.erb
<% if can? :create, Vote %>
  <div class="pull-left vote-arrows">
    <div><%= link_to " ", topic_post_up_vote_path(topic, post), class: "icon-chevron-up #{(current_user.voted(post) && current_user.voted(post).up_vote?) ? 'voted' : '' }" %></div>
    <div><strong><%= post.points %></strong></div>
    <div><%= link_to " ", topic_post_down_vote_path(topic, post), class: "icon-chevron-down #{(current_user.voted(post) && current_user.voted(post).down_vote?) ? 'voted' : '' }" %></div>
  </div>
<% end %>